### PR TITLE
Toward infra-131: using versions.json to drive downloads page

### PR DESCRIPTION
**Pull request by twomice**

### CODE REVIEW

**Comment by twomice** [comment]
Note, this also fixes a few html problems in the download template: closing </strong> without opening it; apparent typos in css classes and inline styles; uneven nesting of civicrm-support divs.

**Comment by colemanw** [comment]
This looks great. Thanks Allen.

**Comment by colemanw** [comment]
Probably the latest & lts version fields should be removed from `cividownload_settings` form?

**Comment by twomice** [comment]
OK, right. Working on that now.

**Comment by twomice** [comment]
Ready for review.

**Comment by colemanw** [comment]
@kurund this looks good to me - want to push it to civicrm.org?

**Comment by kurund** [comment]
@colemanw @twomice oops somehow I missed this earlier. I will try to push this live mid next week

**Comment by colemanw** [comment]
Michael are you going to push this to the live site as well?

**Comment by michaelmcandrew** [comment]
Yes, some time this week. From a cursory look (and not knowing the
background) it looks like I should just be able to pull it live and it will
work, i.e. no need for additional config. Is that correct? Should I test on
test first? If so I will let you and Allen know when it is there and you
can check it out

**Comment by colemanw** [comment]
I think no need for multiple eyes on it unless something looks wrong. I'd say just pull it to the test site, check the download page and if you don't see anything wrong with it, go ahead and merge to live.

**Comment by twomice** [comment]
To confirm: the code is meant to work as written with no additional configuration.

**Comment by michaelmcandrew** [comment]
okiedokie - will pull to test and then live if all ok and then let you know.

**Comment by michaelmcandrew** [comment]
Hey there, wanna check https://civicrm.org/download/list - i pushed it live

**Comment by colemanw** [comment]
Looks great. Nice work @twomice

**Pull request merged**
